name 'juliengk-disk'
version '0.1.0'
source 'git://github.com/juliengk/puppet-module-disk.git'
author 'juliengk'
license 'Apache License, Version 2.0'
summary 'Manage disk quota'
description 'Manage disk quota'
project_page 'https://github.com/juliengk/puppet-module-disk'

dependency 'puppetlabs/stdlib', '>= 4.5.1'
